name: Versionamento

on:
  push:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checar repositório
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Instalar dependências
        run: npm install

      - name: Instalar semver
        run: npm install -g semver

      - name: Criar nova tag caso não exista
        id: create_initial_tag
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [ -z "$(git tag)" ]; then
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'
            git tag -a v0.0.0 -m "Initial release"
            git push origin v0.0.0
          fi

      - name: Calcular nova versão
        id: version
        run: |
          git fetch --tags
          LAST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          if [ -z "$LAST_TAG" ]; then
            LAST_TAG="v0.0.0"
          fi
          echo "Versão Atual: $LAST_TAG"

          # Incrementando a versão de patch
          CURRENT_VERSION=${LAST_TAG#v}
          NEW_VERSION=$(semver -i patch $CURRENT_VERSION)

          echo "Nova versão: $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

      - name: Atualizar versão no package.json
        run: |
          CURRENT_PACKAGE_VERSION=$(node -p "require('./package.json').version")
          if [ "$CURRENT_PACKAGE_VERSION" != "${{ env.new_version }}" ]; then
            npm version ${{ env.new_version }} --no-git-tag-version
          else
            echo "A versão atual já é ${{ env.new_version }}. Nenhuma atualização necessária."
          fi

      - name: Commit e push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          if git diff --quiet; then
            echo "Nenhuma alteração a ser commitada."
          else
            git add package.json
            git commit -m "chore(release): version ${{ env.new_version }}"
            git tag v${{ env.new_version }}
            git push origin master --tags
          fi
